const sampleListings = [{
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    slug: "modern-loft-in-downtown",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "New York City",
    country: "United States",
    taxIncluded: false,
    capacity: 2,
    category: "House",
    actionType: "reserve",
    host: "host001",
    reviews: [],
    averageRating: 0,
    amenities: ["WiFi", "Kitchen", "Air Conditioning", "Parking"],
    availabilityDates: ["2025-09-01", "2025-09-05", "2025-09-10"]
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    slug: "mountain-retreat",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    price: 1000,
    location: "Aspen",
    country: "United States",
    taxIncluded: false,
    capacity: 2,
    category: "Mountain",
    actionType: "check",
    host: "host002",
    reviews: [],
    averageRating: 0,
    amenities: ["WiFi", "Fireplace", "Hot Tub", "Parking"],
    availabilityDates: ["2025-09-03", "2025-09-08", "2025-09-12"]
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    slug: "historic-villa-in-tuscany",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Florence",
    country: "Italy",
    taxIncluded: false,
    capacity: 2,
    category: "Historic",
    actionType: "plan",
    host: "host003",
    reviews: [],
    averageRating: 0,
    amenities: ["WiFi", "Pool", "Kitchen", "Parking"],
    availabilityDates: ["2025-09-02", "2025-09-07", "2025-09-15"]
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    slug: "secluded-treehouse-getaway",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    price: 800,
    location: "Portland",
    country: "United States",
    taxIncluded: false,
    capacity: 2,
    category: "Nature",
    actionType: "book",
    host: "host004",
    reviews: [],
    averageRating: 0,
    amenities: ["WiFi", "Kitchen", "Hammock", "Parking"],
    availabilityDates: ["2025-09-04", "2025-09-09", "2025-09-13"]
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    slug: "beachfront-paradise",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    taxIncluded: false,
    capacity: 2,
    category: "Beach",
    actionType: "reserve",
    host: "host005",
    reviews: [],
    averageRating: 0,
    amenities: ["WiFi", "Pool", "Beach Access", "Parking"],
    availabilityDates: ["2025-09-05", "2025-09-10", "2025-09-15"]
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    slug: "rustic-cabin-by-the-lake",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    taxIncluded: false,
    capacity: 2,
    category: "Lake",
    actionType: "check",
    host: "host006",
    reviews: [],
    averageRating: 0,
    amenities: ["WiFi", "Kitchen", "Fireplace", "Parking"],
    availabilityDates: ["2025-09-06", "2025-09-10", "2025-09-14"]
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    slug: "luxury-penthouse-with-city-views",
    image: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    taxIncluded: false,
    capacity: 2,
    category: "City",
    actionType: "plan",
    host: "host007",
    reviews: [],
    averageRating: 0,
    amenities: ["WiFi", "Pool", "Gym", "Parking"],
    availabilityDates: ["2025-09-07", "2025-09-12", "2025-09-17"]
  },
  {
    title: "Sports Lodge in the Rockies",
    description: "A mountain lodge offering ski-in/ski-out access, guided hikes, and mountain biking adventures.",
    slug: "sports-lodge-in-the-rockies",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c2tpJTIwbG9kZ2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    price: 3200,
    location: "Rocky Mountains",
    country: "United States",
    taxIncluded: false,
    capacity: 2,
    category: "Sports",
    actionType: "book",
    host: "host008",
    reviews: [],
    averageRating: 0,
    amenities: ["WiFi", "Fireplace", "Ski Storage", "Parking"],
    availabilityDates: ["2025-09-08", "2025-09-13", "2025-09-18"]
  },
  {
    title: "Surf Shack in Hawaii",
    description: "Catch the perfect wave every day from this surf shack on Hawaii's North Shore.",
    slug: "surf-shack-in-hawaii",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c3VyZnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    price: 2400,
    location: "Oahu",
    country: "United States",
    taxIncluded: false,
    capacity: 2,
    category: "Sports",
    actionType: "reserve",
    host: "host009",
    reviews: [],
    averageRating: 0,
    amenities: ["WiFi", "Surfboards", "Kitchen", "Parking"],
    availabilityDates: ["2025-09-09", "2025-09-14", "2025-09-19"]
  },
  {
    title: "Adventure Camp in New Zealand",
    description: "Paragliding, rafting, and zip-lining — this adventure camp has it all for the sports enthusiast.",
    slug: "adventure-camp-in-new-zealand",
    image: "https://peakvisor.com/photo/Medicine-Bow-National-Forest-Wyoming-Campgrounds.jpg",
    price: 2700,
    location: "Queenstown",
    country: "New Zealand",
    taxIncluded: false,
    capacity: 2,
    category: "Sports",
    actionType: "check",
    host: "host010",
    reviews: [],
    averageRating: 0,
    amenities: ["WiFi", "Adventure Gear", "Guided Tours", "Parking"],
    availabilityDates: ["2025-09-10", "2025-09-15", "2025-09-20"]
  },
  {
    title: "Kayak Haven in Norway",
    description: "Paddle through the pristine fjords of Norway with guided kayak tours and stunning scenery.",
    slug: "kayak-haven-in-norway",
    image: "https://images.unsplash.com/photo-1505852679233-d9fd70aff56d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 2100,
    location: "Geiranger",
    country: "Norway",
    taxIncluded: false,
    capacity: 2,
    category: "Sports",
    actionType: "plan",
    host: "host011",
    reviews: [],
    averageRating: 0,
    amenities: ["WiFi", "Kayak Equipment", "Guided Tours", "Parking"],
    availabilityDates: ["2025-09-11", "2025-09-16", "2025-09-21"]
  }];

module.exports = { data: sampleListings };